### ISSUE TITLE
Will the code be further maintained to be compatible with wrf4.4?

### ISSUE THREAD

**Issue by OMGTaylor0814** [jcwarner-usgs/COAWST#145]
Hi There
I wonder if you will further maintain the code to be wrf4.4 compatible? Perhaps this question is more presumptuous, because I am using wrf version 4.4 now, and some colleagues have made many modifications to the code of this version. I'm not sure if I can replace wrf/wps in git hub with my own wrf code.
Secondly I wonder if there are some tutorials for coawst compilation?

Best regards,
Junius

**Comment by jcwarner-usgs** [comment]
we have updated the code to WRF 4.4., SWAN 41.45, WW3 7.14.1, and roms to what ever was there about 4 weeks ago.
I am waiting to hear from our admin for a new release policy.  i have to manage the git site a little differently.  as soon as that gets worked out i will put out a new version.
do you want an early version to test?
-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner

________________________________
From: OMGTaylor0814 ***@***.***>
Sent: Sunday, June 11, 2023 9:45 PM
To: jcwarner-usgs/COAWST ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [jcwarner-usgs/COAWST] Will the code be further maintained to be compatible with wrf4.4? (Issue #145)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi There
I wonder if you will further maintain the code to be wrf4.4 compatible? Perhaps this question is more presumptuous, because I am using wrf version 4.4 now, and some colleagues have made many modifications to the code of this version. I'm not sure if I can replace wrf/wps in git hub with my own wrf code.
Secondly I wonder if there are some tutorials for coawst compilation?

Best regards,
Junius

**Comment by douglasnehme** [comment]
John, Hernan Arango tagged the ROMS svn version -r 1172 as 4.1, because it's relatively stable. If it's not the ROMS version in the next COAWST release, do you think would be possible to update it?

Best regards.

**Comment by hga007** [comment]
We started the process of consolidating our **ROMS** repositories. We have too many research **git** and **svn** repositories. In a few days, we will host the git repository on **GitHub** and will have several branches when cloning **ROMS** source code:

- **`master`**: Tagged versions and latest stable release version of **ROMS**
- **`develop`**: Main developing branch of **ROMS**. Not for public consumption but passes the internal tests. It is recommended for **ROMS** superusers and beta testers.
- **`feature branches`**: Research and new development branches recommended to superusers and beta testers:
  -   **`feature/kernels`**: Major update to **ROMS** numerical kernels (**omega.F** and **step2d.F**)
  -  **`feature/seaice`**: Native ROMS sea-ice model refactoring and development
  - **`feature/wec`**: Wave Effects on Currents algorithms adopted from **COAWST**

I suggest waiting until we are done with the refactoring and the regular and novice user to focus on either the **master** or **develop** branches. The restructuring facilitates the maintenance of **ROMS** source code, the development of new algorithms, and updating of the **COAWST** system.

We still recommend users to interact via https://www.myroms.org/forum for discussions and problems. There is plenty of information at https://www.myroms.org/wiki
