### ISSUE TITLE
Simulation blows up in the first step

### ISSUE THREAD

**Issue by chunlei666** [jcwarner-usgs/COAWST#205]
Sorry to bother you again John

I tried to run a real ROMS-SWAN-WRF case with nesting grids. however, the model exploded in the first step. 
![image](https://github.com/DOI-USGS/COAWST/assets/44604298/4c1bd391-c2bc-4cf9-a04b-56cb849626be)
![image](https://github.com/DOI-USGS/COAWST/assets/44604298/68bfb7ce-81d3-4e39-b6f1-683474503426)

I am new to the ocean and wave models, and do not know how to fix it. I built the input files following the user guide. 
Could you help me with this? I am grateful for your help.

**Comment by jcwarner-usgs** [comment]
i would look at the roms rst file.  see where the issue is.  lateral boundary? wet/dry line?  steep topography?  
did you run this setup without nested grids.  take it one step at a time.

**Comment by chunlei666** [comment]
the outputs for roms did not come out. I tried the no-nesting case, and it gave me the Errfile. 
![image](https://github.com/DOI-USGS/COAWST/assets/44604298/565d5d5e-c014-42f9-9770-5808901c9b02)
i think i need to rebuild the boundary

**Comment by chunlei666** [comment]
Confused. No error comes out when i build the boundary from the Hycom, only a warning "reversing zlev to arrange as deep to shallow ". i do not know what that mean.

**Comment by jcwarner-usgs** [comment]
i think you are confusing the boundaries between roms and swan.
I suggest you try to run roms by itself, then roms with nesting by itself.
then swan by itself, swan with nesting by itself,
then combine them.

the hycom 'warning' is just a warning. that warning happens when it reads the hycom data.

for the first moment is zero - i am not sure.  but you probably have something wrong with swan tpar files.
