### ISSUE TITLE
COAWST fails to build WRF in Sandy Case

### ISSUE THREAD

**Issue by HathewayWill** [jcwarner-usgs/COAWST#220]
@jcwarner-usgs 
I am trying to automate the installation of COAWST with all the libraries and files installed for users.

I have attached my script that I have created as well as a log file with the output from the build_coawst.sh.

There seems to be a module in WRF that isn't found.  I have seen this error before in older versions of WRF that was fixed in 4.5.2. I'm not sure which version COAWST is coupled with.

Please help if you can.

Regards
[Error.zip](https://github.com/DOI-USGS/COAWST/files/14031839/Error.zip)

**Comment by jcwarner-usgs** [comment]
right near the top i see
" gfortran: error: unrecognized command-line option ‘-assume’"
there is a flag "-assume byterecl " this is for writing out binary files, like the matlab files for swan.
suggest you comment that out.  It would be in Compilers/Linux-gfortran.mk

that error cascades to other issues:
make: *** [makefile:603: mct_params] Error 1
the mct_params is needed for the coupling.

work on fixing the bytrecl build issue first.

**Comment by HathewayWill** [comment]
@jcwarner-usgs  Thank you sir.  I'll try that and let you know.

Also how do I enable the -j feature for building in parallel?

**Comment by HathewayWill** [comment]
Good morning sir,,

The removal of -assume byterecl allowed WRF to almost be built.  Everything but wrf.exe was built and that caused swan to fail because it couldn't find wrf.exe I think.

Looking at the build log at line 5266 gives a ld status error 1 due to a undefined reference to main.

Not sure what could be causing this.

Could you take a look at the log?

Regards,
WH
[new_error.zip](https://github.com/DOI-USGS/COAWST/files/14040599/new_error.zip)

**Comment by jcwarner-usgs** [comment]
...[ 97%] Linking Fortran executable ../bin/swan.exe
..... [ 97%] Built target swan.exe
So it did build swan.exe.  swan is all good.  but actually i dont need swan.exe
i dont need wrf.exe
i dont need roms.exe
All i need are the libs, and they get pulled together to make a coawstM.

you dont need to worry about
.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
Command exited with non-zero status 1
0.16user 0.05system 0:00.21elapsed 100%CPU (0avgtext+0avgdata 126200maxresident)k
0inputs+110576outputs (0major+59869minor)pagefaults 0swaps
make[2]: [Makefile:17: em_wrf] Error 1 (ignored)

that is ok.

your problem is:

ext_pnc_inquire_filename ....  you are using parallel netcdf.
for some reason we can not use paralle netcdf.
there was another user who figured out a way to do that, but i have not looked at that yet.

so do this:
export PNETCDF=
make it blank, so wrf does not see anything.
we dont want this:  NetCDF built with PnetCDF: yes
we want it to say no.

**Comment by HathewayWill** [comment]
Thank you!

**Comment by jcwarner-usgs** [comment]
or maybe it is

export PNETCDFPATH = ' '

**Comment by jcwarner-usgs** [comment]
Also how do I enable the -j feature for building in parallel?
when you type the build 
./bulid_coawst.sh -j 6
or what ever number of procs you want to allocate to the build.

**Comment by HathewayWill** [comment]
> or maybe it is
> 
> export PNETCDFPATH = ' '

ill just remove pnetcdf from the installlation.  The only reason i had it was for wrf to run in parallel so that it runs faster. @jcwarner-usgs

**Comment by HathewayWill** [comment]
@jcwarner-usgs 

I believe everything is fixed now.

Here are the log files.

Is there a tutorial to run a test case to make sure it is coupled with the three models> (ROMS <-> WRF <-> SWAN)
[Sucess??.zip](https://github.com/DOI-USGS/COAWST/files/14042659/Sucess.zip)

**Comment by jcwarner-usgs** [comment]
there wasnt any files in that zip.
There are lots of descriptions/test cases in the COAWST User Manual.doc.
-j

**Comment by HathewayWill** [comment]
should be a folder called sucess with the logs...odd it didn't upload ill toss it here.

[build_coawst.log](https://github.com/DOI-USGS/COAWST/files/14044384/build_coawst.log)
[build_coawst.sh.txt](https://github.com/DOI-USGS/COAWST/files/14044385/build_coawst.sh.txt)
[coawst.log](https://github.com/DOI-USGS/COAWST/files/14044386/coawst.log)
[COAWST_GNU.sh.txt](https://github.com/DOI-USGS/COAWST/files/14044388/COAWST_GNU.sh.txt)

**Comment by jcwarner-usgs** [comment]
did you get a coawstM ?
ls -ltr
is there a coawstM?  if you got that file , you are good.

**Comment by HathewayWill** [comment]
@jcwarner-usgs 

Great got it!

**Comment by HathewayWill** [comment]
Thank you.  I plan to implement it with the next WRF release 4.7.0
