### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by erholz** [jcwarner-usgs/COAWST#56]
Hi,

I'm trying to run COAWST on a [remote machine](https://portal.tacc.utexas.edu/user-guides/stampede2#system-overview) and haven't had any success with compiling yet.  I've tried compiling WRF only (following the most recent webinar recordings), ROMS only, and the veg_test example case.  One error/warning I consistently get is that folders are "not a working directory", which I think is because I'm not using SVN.  Could that be a source of my issue?  I've attached the build logs for three examples.  The WRF warnings are a little difficult to interpret, but I see that the ROMS and coupled model have trouble accessing or finding things in the INCLUDE directory.

Many thanks for your help!

P.S. I've tried using option 15 and 70 (KNL MIC nodes for Stampede2 machine), to build WRF but get essentially the same results.

[vegtest.log](https://github.com/jcwarner-usgs/COAWST/files/7367430/vegtest.log)
[wrfonly_opt15.log](https://github.com/jcwarner-usgs/COAWST/files/7367432/wrfonly_opt15.log)
[romsonly.log](https://github.com/jcwarner-usgs/COAWST/files/7367433/romsonly.log)

**Comment by jcwarner-usgs** [comment]
ok i am not totally sure what all is going on, but here are some suggestions:

-for the wrf only, i see
./clean_kpp: Permission denied.
maybe look on the permissions for that file.

i also see
 -L/usr/local/mct/lib -lmct -lmpeu  .......  lnetcdf -L/opt/apps/intel18/hdf5/1.10.4/x86_64/lib -lhdf5 -lhdf5_hl -lz
/opt/apps/gcc/6.3.0/bin/ld: cannot find -lmct
/opt/apps/gcc/6.3.0/bin/ld: cannot find -lmpeu

what is in /usr/local/mct/lib?
is that the location of your mct?
you might need to set them with
EXPORT MCT_INCDIR=/path to mct includes
EXPORT MCT_LIBDIR=/path to mct libs

-for roms only, i am not sure, but lets do an
ls -ltr ROMS/Bin
i see "/bin/sh: ./ROMS/Bin/sfmakedepend: Permission denied"
so that might be an issue?

-j


John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner


________________________________
From: erholz ***@***.***>
Sent: Monday, October 18, 2021 1:32 PM
To: jcwarner-usgs/COAWST ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [jcwarner-usgs/COAWST] compiling issues (Issue #56)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi,

I'm trying to run COAWST on a remote machine<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.tacc.utexas.edu%2Fuser-guides%2Fstampede2%23system-overview&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634503797%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2Yikv5cIzxpGx5bS8SfNvRxlv028sm8IMBMK%2FXsbD6g%3D&reserved=0> and haven't had any success with compiling yet. I've tried compiling WRF only (following the most recent webinar recordings), ROMS only, and the veg_test example case. One error/warning I consistently get is that folders are "not a working directory", which I think is because I'm not using SVN. Could that be a source of my issue? I've attached the build logs for three examples. The WRF warnings are a little difficult to interpret, but I see that the ROMS and coupled model have trouble accessing or finding things in the INCLUDE directory.

Many thanks for your help!

P.S. I've tried using option 15 and 70 (KNL MIC nodes for Stampede2 machine), to build WRF but get essentially the same results.

vegtest.log<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwarner-usgs%2FCOAWST%2Ffiles%2F7367430%2Fvegtest.log&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634513751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f65xr9GtIkRWYy11gbOyHSjQnQGULJ2SqTSAQIUJc74%3D&reserved=0>
wrfonly_opt15.log<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwarner-usgs%2FCOAWST%2Ffiles%2F7367432%2Fwrfonly_opt15.log&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634513751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8V8HmYXl23rfrWBta0%2FhAU08BuXh9vYBdOe2s%2F75SMA%3D&reserved=0>
romsonly.log<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwarner-usgs%2FCOAWST%2Ffiles%2F7367433%2Fromsonly.log&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634523709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wHeCGC2cndXdiOYGTmWGdqG4rveWhm4FbW35s10ZIHk%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwarner-usgs%2FCOAWST%2Fissues%2F56&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634523709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uf0343v3Fpte5H1WHI9yJBvUUvyr8q7kjnM0FQ72q2I%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZ6MOAYTZ2CJLFG532NCGLUHRKZNANCNFSM5GHF6CUQ&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634523709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SjhzVFdKBa0bTQhC1ViYdwgA1fjnWwz%2BkIjD88Wcemc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634533663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vCtu2qVn%2BzQPY8%2FBHK1Mmdcw3d0G%2Brx%2FMQbNU2OK2E8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjcwarner%40usgs.gov%7Cdf30a4735cc644c1c4ce08d9925d495b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637701751634533663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N1iDR%2Ff5a6oR1kuq0msppG0ImXML5mm05RhLVFxkCZI%3D&reserved=0>.

**Comment by erholz** [comment]
Hi John,

Thanks for helping identify those permission issues.  Fixing those and resetting the correct MCT location seemed to fix the compiling issue for the roms only, wrf only, and veg_test cases.

Thanks again!
Liz

**Comment by jcwarner-usgs** [comment]
great !!
-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner


________________________________
From: erholz ***@***.***>
Sent: Tuesday, October 19, 2021 3:19 PM
To: jcwarner-usgs/COAWST ***@***.***>
Cc: Warner, John C ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [jcwarner-usgs/COAWST] compiling issues (Issue #56)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi John,

Thanks for helping identify those permission issues. Fixing those and resetting the correct MCT location seemed to fix the compiling issue for the roms only, wrf only, and veg_test cases.

Thanks again!
Liz

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwarner-usgs%2FCOAWST%2Fissues%2F56%23issuecomment-947033735&data=04%7C01%7Cjcwarner%40usgs.gov%7C9229c1d7d6b147342a1808d993356304%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637702679773987549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RYEnDzrSnJYXHf8P%2FfwP59Zps92dtopHRqdhVqS7YWI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZ6MOEQ33ZRS6QN6LVU7RDUHXADDANCNFSM5GHF6CUQ&data=04%7C01%7Cjcwarner%40usgs.gov%7C9229c1d7d6b147342a1808d993356304%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637702679773997502%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5E9w0oe4MxglxbVEBpMDFVrfg5SMtx%2Fddq%2BIDlI9mLU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjcwarner%40usgs.gov%7C9229c1d7d6b147342a1808d993356304%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637702679773997502%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fOww2I1YL86dODvhrHVhZ8HdXvee%2FZgAG9Um9uiyUvI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjcwarner%40usgs.gov%7C9229c1d7d6b147342a1808d993356304%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637702679774007461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X8Gf2uIO%2FKKg1%2BXXU4PO6Fp164nqNaap%2B3OvOieatX8%3D&reserved=0>.
