### ISSUE TITLE
Unusual low SST when running an interannual ROMS-WRF coupled COAWST.

### ISSUE THREAD

**Issue by PeterRony** [jcwarner-usgs/COAWST#79]
Dear all,
We are trying to do a coupled simulation for a month. Though the model runs, the SST seems to be unrealistic. We are initializing the ROMS ocean model using INCOIS GODAS and WRF-4.0.3 using NCEP-FNL. The grid resolution is 9km for both models. I am attaching the screenshot of the simulated SST of the 4th day.  Any help in this regard will be highly appreciated. Thanks in advance.
![SST_wrf_4thday](https://user-images.githubusercontent.com/58770630/168219984-1dd1e608-039e-41aa-a81c-47cbe8620322.png)

**Comment by jcwarner-usgs** [comment]
are you using #define ATM2OCN_FLUXES ?
maybe you could look at the individual terms in the heat flux (gsw, glw, hfx, lh).

-j

**Comment by PeterRony** [comment]
Yes, I am using #define ATM2OCN_FLUXES in the experiment. I am attaching the log file here. Also, I was able to run standalone WRF without any issues and the outputs are reasonable.
[coawst.log.txt](https://github.com/jcwarner-usgs/COAWST/files/8690124/coawst.log.txt)

**Comment by jcwarner-usgs** [comment]
So i am not exactly sure what to suggest, but here are a few things.

-when you run standalone WRF without any issues, what does that mean?  the issue here is ocean SST, so what SST did you use?

-You say the SST is too cool, but i am not familiar with this area at this moment in time.
How much cooler is it?  did it happen right away, or slowly over the days?

-Did you run ROMS by itself, forced with ECMWF data or something like that to see if roms is ok?

-Did you activate solar_source?  that can help to distribute the fluxes into the water column.

-i see the vertical s params are kinda high:
level   S-coord     Cs-curve   Z   at hmin       at hc    half way     at hmax
    32   0.0000000   0.0000000        0.000       0.000       0.000       0.000
    31  -0.0312500  -0.0000461       -0.279      -0.156      -0.412      -0.510
    30  -0.0625000  -0.0001867       -0.564      -0.313      -1.029      -1.426
    29  -0.0937500  -0.0004285       -0.856      -0.471      -1.868      -2.776
    28  -0.1250000  -0.0007831       -1.155      -0.629      -2.952      -4.612
    27  -0.1562500  -0.0012675       -1.463      -0.788      -4.320      -7.005
    26  -0.1875000  -0.0019050       -1.780      -0.947      -6.021     -10.056 
.....
so your top layer is 0.5 m thick.  Can you look at other layers below that?

-just for fun, try to set the wrf-roms coupling to be 1 day .  that is way too infrequent but if roms is still cooling off rapidly then it is not the coupling. it is roms.

-look at the vertical mixing in the model.  does it seem reasonable. ?

-is the cooling just at the surface or down through the water column.

you will need to look and try some things here.

**Comment by PeterRony** [comment]
Thank you, Dr. Warner. As per your suggestions, We have carried out standalone ROMS forced with ECMWF. It had some problems and we could rectify them. And we initialized the COAWST model with the ROMS model spun up for 20 years. Now the COAWST model results are okay.
