### ISSUE TITLE
for_main.o error in ./coawst.bash compile with intel compiler,  impi 

### ISSUE THREAD

**Issue by mjaee** [jcwarner-usgs/COAWST#81]
Dear John, 

Hello, I have tried to compile COAWST v3.3.1 by coawst.bash. (Because I have WRFv3.9.1.1 output...)
But 'wrf.exe' was not made because of 'for_main.o' error. 

----------------------------------------------------------------------------------------------------------------------------------------
time mpiifort -f90=ifort -o wrf.exe  -O3 -ip -fp-model precise -w -ftz -align all -fno-alias -FR -convert big_endian -fp-model fast=2 -no-heap-arrays -no-prec-div -no-prec-sqrt -fno-common -xCOMMON-AVX512  -ip -fp-model fast=2 -no-prec-div -no-prec-sqrt -ftz -align all -fno-alias -fno-common -xCOMMON-AVX512  wrf.o ../main/module_wrf_top.o libwrflib.a /scratch/e1122a11/COAWST/WRF/external/fftpack/fftpack5/libfftpack.a /scratch/e1122a11/COAWST/WRF/external/io_grib1/libio_grib1.a /scratch/e1122a11/COAWST/WRF/external/io_grib_share/libio_grib_share.a /scratch/e1122a11/COAWST/WRF/external/io_int/libwrfio_int.a -L/scratch/e1122a11/COAWST/WRF/external/esmf_time_f90 -lesmf_time /scratch/e1122a11/COAWST/WRF/external/RSL_LITE/librsl_lite.a /scratch/e1122a11/COAWST/WRF/frame/module_internal_header_util.o /scratch/e1122a11/COAWST/WRF/frame/pack_utils.o  -L/scratch/e1122a11/COAWST/WRF/external/io_netcdf -lwrfio_nf -L/apps/compiler/intel/19.0.5/impi/2019.5.281/applib2/mic-knl/netcdf-hdf5-parallel/4.6.1/lib -lnetcdff -lnetcdf  -L/scratch/e1122a11/COAWST/WRF/external/io_pnetcdf -lwrfio_pnf -L/apps/compiler/intel/19.0.5/impi/2019.5.281/applib2/mic-knl/parallel-netcdf/1.10.0/lib -lpnetcdf   -L/apps/compiler/intel/19.0.5/impi/2019.5.281/applib2/mic-knl/hdf5-parallel/1.10.2/lib -lhdf5_fortran -lhdf5 -lm -lz   -L/scratch/e1122a11/COAWST/Lib_min/lib -lmct -lmpeu -L/apps/compiler/intel/19.0.5/impi/2019.5.281/applib2/mic-knl/netcdf-hdf5-parallel/4.6.1/lib -lnetcdf
**_/apps/compiler/intel/19.0.5/compilers_and_libraries_2019.5.281/linux/compiler/lib/intel64_lin/for_main.o: In function `main':
for_main.c:(.text+0x2e): undefined reference to `MAIN__'_**
0.94user 1.15system 0:04.29elapsed 48%CPU (0avgtext+0avgdata 149396maxresident)k
206688inputs+126264outputs (0major+74552minor)pagefaults 0swaps
make[2]: [em_wrf] Error 1 (ignored)
make[2]: Leaving directory `/scratch/e1122a11/COAWST/WRF/main'
--------------------------------------------------------------------------------------------------------------------------------------------------

Error script is attached above, and script used for compile is ' ./coawst.bash -j 4 -nocleanwrf >&compile.log'
WRF configure is executed first because of using mpiifort (not mpif90).
so, i changed mpif90 -> mpiifort in ./Compiler/Linux-ifort.mk also.

It's an old version, but can you help me?

[compile_log.txt](https://github.com/jcwarner-usgs/COAWST/files/8868402/compile_log.txt)
[coawst.bash.txt](https://github.com/jcwarner-usgs/COAWST/files/8868404/coawst.bash.txt)
[configure.wrf.txt](https://github.com/jcwarner-usgs/COAWST/files/8868406/configure.wrf.txt)
[Linux-ifort.mk.txt](https://github.com/jcwarner-usgs/COAWST/files/8868408/Linux-ifort.mk.txt)
[wrf2roms_advanced.h.txt](https://github.com/jcwarner-usgs/COAWST/files/8869691/wrf2roms_advanced.h.txt)

**Comment by jcwarner-usgs** [comment]
i can try.
looks like a couple of things here.
-the "wrf.exe' was not made because of 'for_main.o' error."  is ok.  I do not let wrf make an exe if it is coupled. we can only have one exe.  so that is fine.  the compilation kept going.

- if you look in the compile .log you see
... /e1122a11/COAWST/Projects/wrf2roms_advanced/wrf2roms_advanced.h:63:0: warning: extra tokens at end of #undef directive [enabled by default]
 # undef SSH_TIDES  //undef by kimjy
In file included from ROMS/Include/cpp
i would change that line from
 # undef SSH_TIDES  //undef by kimjy
to
#undef SSH_TIDES  /*undef by kimjy */
and see if that error goes away.

-then there are many instances of problems like this:
 undefined reference to `netcdf_mp_nf90_def_dim_'
./Build/libUTIL.a(def_info.o): In function `def_info_':
def_info.f90:(.text+0x38d): undefined reference to `netcdf_mp_nf90_put_att_text_'
so I think your netcdf need to have the fortran interface in it.
if you do   nf-config --all
here is what i get:

This netCDF-Fortran 4.4.4 has been built with the following features:
  --cc        -> mpiicc
  --cflags    ->  -I/vortexfs1/apps/impistack-1.0/include -I/vortexfs1/apps/impistack-1.0/include

  --fc        -> mpiifort
  --fflags    -> -I/vortexfs1/apps/impistack-1.0/include
  --flibs     -> -L/vortexfs1/apps/impistack-1.0/lib -lnetcdff -L/vortexfs1/apps/impistack-1.0/lib -lnetcdf -lnetcdf
  --has-f90   -> no
  --has-f03   -> yes

  --has-nc2   -> yes
  --has-nc4   -> yes

  --prefix    -> /vortexfs1/apps/impistack-1.0
  --includedir-> /vortexfs1/apps/impistack-1.0/include
  --version   -> netCDF-Fortran 4.4.4

**Comment by mjaee** [comment]
dear John, 

Until now, i think errors about **_'netcdf_mp_nf90_def_dim_' ./Build/libUTIL.a(def_info.o): In function'_** is due to absence of wrf.exe...!

i added library link line into location in which error occurs. (-L/~~~/ -lnetcdf -lnetcdff)

then, it works out!

thank you for your help :)

**Comment by jcwarner-usgs** [comment]
glad it is working for you !
